user_int = int(input('Enter integer (32 - 126):\n'))
print('Enter float:')
second_number = float(input())
print('Enter character:')
third_entry = input()
print('Enter string:')
fourth_entry = str(input())
print(user_int,end=' ')
print(second_number,end=' ')
print(third_entry,end=' ')
print(fourth_entry)
print(fourth_entry,end=' ')
print(third_entry,end=' ')
print(second_number,end=' ')
print(user_int)
print(user_int, 'converted to a character is', chr(user_int))